declare function require(name: string): any;
declare const process: { cwd(): string };

const { readFileSync } = require("fs");
const { join } = require("path");

function assertIncludes(actual: string, expected: string) {
  if (!actual.includes(expected)) {
    throw new Error(`期望 SignalTriageWorkbench.tsx 包含 ${expected}`);
  }
}

function assertNotIncludes(actual: string, expected: string) {
  if (actual.includes(expected)) {
    throw new Error(`期望 SignalTriageWorkbench.tsx 不包含 ${expected}`);
  }
}

function assert(condition: boolean, message: string) {
  if (!condition) {
    throw new Error(message);
  }
}

const workbenchSource = readFileSync(
  join(process.cwd(), "src", "pages", "SignalTriageWorkbench", "SignalTriageWorkbench.tsx"),
  "utf8",
);
const signalUiSource = readFileSync(join(process.cwd(), "src", "pages", "SignalTriageWorkbench", "signalUi.ts"), "utf8");
const reviewUiSource = readFileSync(join(process.cwd(), "src", "pages", "SignalTriageWorkbench", "reviewUi.ts"), "utf8");

assertIncludes(workbenchSource, "buildProductScopeEvidenceMatrix");
assertIncludes(workbenchSource, "productScopeAdGroupDiagnosisRows");
assertIncludes(workbenchSource, "buildNoActionableManualGate");
assertIncludes(workbenchSource, "buildProductScopeCandidateGapExplanation");
assertIncludes(workbenchSource, "ProductScopeEvidenceMatrix");
assertIncludes(workbenchSource, "ProductScopeAdGroupDiagnosisRow");
assertIncludes(workbenchSource, "NoActionableManualGate");
assertIncludes(workbenchSource, "const productScopeEvidenceMatrix = useMemo");
assertIncludes(workbenchSource, "const productScopeEvidenceRouteGuide = useMemo");
assertIncludes(workbenchSource, "const productScopeAdGroupDiagnosis = useMemo");
assertIncludes(workbenchSource, "const noActionableManualGate = useMemo");
assertIncludes(workbenchSource, "const productScopeCandidateGapExplanation = useMemo");
assertIncludes(workbenchSource, "matrix={productScopeEvidenceMatrix}");
assertIncludes(workbenchSource, "ProductScopeAdGroupDiagnosisPanel rows={productScopeAdGroupDiagnosis}");
assertIncludes(workbenchSource, "function ProductScopeEvidenceMatrixPanel");
assertIncludes(workbenchSource, "function ProductScopeAdGroupDiagnosisPanel");
assertIncludes(workbenchSource, 'aria-label="广告组内投放商品表现"');
assertIncludes(workbenchSource, "row.advertisedProductPerformance");
assertIncludes(workbenchSource, "function ProductScopeEvidenceRouteGuidePanel");
assertIncludes(workbenchSource, "function ProductScopeCandidateGapExplanationPanel");
assertIncludes(workbenchSource, "function NoActionableManualGatePanel");
assertIncludes(workbenchSource, "effective-${index}-${term.label}");
assertIncludes(workbenchSource, "zero-${index}-${term.label}");
assertIncludes(workbenchSource, 'aria-label="对象证据矩阵"');
assertIncludes(workbenchSource, 'aria-label="广告证据链导览"');
assertIncludes(workbenchSource, 'aria-label="广告路径可落地判断"');
assertIncludes(workbenchSource, "guide.summary");
assertIncludes(workbenchSource, "guide.decision.currentJudgement");
assertIncludes(workbenchSource, "guide.decision.doesNotProve");
assertIncludes(workbenchSource, "guide.decision.nextManualStep");
assertIncludes(signalUiSource, "buildProductScopeEvidenceRouteDecision");
assertIncludes(signalUiSource, "哪些广告对象真的有广告数据");
assertIncludes(signalUiSource, "先看经营入口，再看广告 ASIN、广告组、投放词/搜索词/广告位");
assertIncludes(signalUiSource, "AI 信号诊断、人工确认和 7/14 天复盘");
assertIncludes(signalUiSource, "AI 准入 -> 人工确认 -> 7/14 天复盘");
assertIncludes(signalUiSource, "未完成人工留痕和 ready 复盘前，不能保存 ReviewRecord");
assertIncludes(signalUiSource, 'layerId: "ai_signal"');
assertIncludes(signalUiSource, 'layerId: "manual_confirmation"');
assertIncludes(signalUiSource, 'layerId: "review"');
assertIncludes(signalUiSource, "复盘门槛：先有人工留痕和 7d / 14d ReviewTodo");

const diagnosisPanelIndex = workbenchSource.indexOf('<section className="diagnosisPanel">');
const routeGuideRenderIndex = workbenchSource.indexOf(
  "{productScopeEvidenceRouteGuide && <ProductScopeEvidenceRouteGuidePanel guide={productScopeEvidenceRouteGuide} />}",
);
const adGroupDiagnosisRenderIndex = workbenchSource.indexOf(
  "{productScopeAdGroupDiagnosis.length > 0 && <ProductScopeAdGroupDiagnosisPanel rows={productScopeAdGroupDiagnosis} />}",
);
const selectedSignalBranchIndex = workbenchSource.indexOf("{selectedSignal ? (");
const selectedSignalScopeContextRenderIndex = workbenchSource.indexOf(
  "<SelectedSignalScopeContextStrip context={selectedSignalScopeContext} />",
);
const searchIntentFocusContextRenderIndex = workbenchSource.indexOf(
  "<SearchIntentFocusContextStrip context={selectedSearchIntentFocusContext} />",
);
const signalDiagnosisRenderIndex = workbenchSource.indexOf("<SignalDiagnosis");
assert(diagnosisPanelIndex >= 0, "诊断区必须存在");
assert(routeGuideRenderIndex > diagnosisPanelIndex, "广告证据链导览必须渲染在诊断区内");
assert(routeGuideRenderIndex < selectedSignalBranchIndex, "广告证据链导览不能被单条信号选中状态挡住");
assert(adGroupDiagnosisRenderIndex > diagnosisPanelIndex, "广告组问题定位必须渲染在诊断区内");
assert(adGroupDiagnosisRenderIndex < selectedSignalBranchIndex, "广告组问题定位不能被单条信号选中状态挡住");
assertIncludes(workbenchSource, "buildSelectedSignalScopeContext");
assertIncludes(workbenchSource, "selectedSignalScopeContext");
assertIncludes(workbenchSource, "buildSearchIntentFocusContext");
assertIncludes(workbenchSource, "selectedSearchIntentFocusContext");
assertIncludes(workbenchSource, "function evidenceFactDisplayLabel");
assertIncludes(workbenchSource, 'label === "Parent ASIN 搜索词表现聚合"');
assertIncludes(workbenchSource, 'return "搜索意图分组";');
assertIncludes(workbenchSource, "function SelectedSignalScopeContextStrip");
assertIncludes(workbenchSource, "function SearchIntentFocusContextStrip");
assertIncludes(workbenchSource, 'aria-label="选中信号与当前诊断入口关系"');
assertIncludes(workbenchSource, 'aria-label="广告搜索词表现复核与当前信号关系"');
assertIncludes(signalUiSource, "buildSelectedSignalScopeContext");
assertIncludes(signalUiSource, "buildSearchIntentFocusContext");
assertIncludes(signalUiSource, "当前诊断入口仍是");
assertIncludes(signalUiSource, "选中信号只决定中间证据和右侧人工确认对象");
assertIncludes(signalUiSource, "不能自动归因");
assertIncludes(signalUiSource, "视角聚合广告中实际产生表现的用户搜索词行");
assertIncludes(signalUiSource, "Parent ASIN 广告搜索词表现复核「${focusLabel}」只是分析分组");
assertIncludes(signalUiSource, "Parent ASIN 广告搜索词表现复核用于聚合同类广告搜索词表现");
assertIncludes(signalUiSource, "经营诊断入口");
assertIncludes(signalUiSource, "搜索词聚合口径");
assertIncludes(signalUiSource, "当前诊断对象");
assertIncludes(workbenchSource, "context.pathItems.map");
assertIncludes(workbenchSource, "Parent ASIN 广告搜索词表现复核");
assertIncludes(workbenchSource, "搜索意图分组");
assertNotIncludes(workbenchSource, "<b>聚合标签</b>");
assertIncludes(signalUiSource, "以后端预检确认的 SearchTerm 稳定对象为准");
assertNotIncludes(signalUiSource, "右侧人工动作也必须落到这条 SearchTerm 的稳定对象");
assert(selectedSignalScopeContextRenderIndex > selectedSignalBranchIndex, "选中信号入口关系必须渲染在信号详情分支内");
assert(selectedSignalScopeContextRenderIndex < signalDiagnosisRenderIndex, "选中信号入口关系必须先于信号详情展示");
assert(searchIntentFocusContextRenderIndex > selectedSignalScopeContextRenderIndex, "广告搜索词聚合承接必须跟在入口关系之后");
assert(searchIntentFocusContextRenderIndex < signalDiagnosisRenderIndex, "广告搜索词聚合承接必须先于信号详情展示");

assertIncludes(workbenchSource, 'aria-label="Parent ASIN 经营诊断路径"');
assertIncludes(workbenchSource, 'aria-label="诊断入口路径说明"');
assertNotIncludes(workbenchSource, 'aria-label="经营商品优先入口说明"');
assertIncludes(workbenchSource, "productScopePathPreview");
assertIncludes(workbenchSource, "buildProductScopeFirstScreenSummary");
assertIncludes(workbenchSource, "productScopeBusinessPreview");
assertIncludes(workbenchSource, "useRef");
assertIncludes(workbenchSource, "workbenchGridRef");
assertIncludes(workbenchSource, "isEvidenceDrilldownFocused");
assertIncludes(workbenchSource, "setIsEvidenceDrilldownFocused");
assertIncludes(workbenchSource, "handleOpenProductScopeEvidenceDrilldown");
assertIncludes(workbenchSource, "function handleSelectSearchIntent");
assertIncludes(workbenchSource, "function handleSelectQueueFilter");
assertIncludes(workbenchSource, "buildSearchTermAdContextRows(signal)");
assertIncludes(workbenchSource, "row.reviewPriority");
assertIncludes(workbenchSource, "row.reviewReason");
assertIncludes(workbenchSource, "selectedSearchIntentScopeId");
assertIncludes(workbenchSource, "activeSearchIntentLabel");
assertIncludes(workbenchSource, "function clearSearchIntentFocus");
assertIncludes(workbenchSource, "setSelectedSearchIntentScopeId(null);");
assertIncludes(workbenchSource, "if (isSameScopedFocus)");
assertIncludes(workbenchSource, "clearSearchIntentFocus();");
assertIncludes(workbenchSource, "return;");
assertIncludes(workbenchSource, "setSelectedSearchIntentScopeId(activeProductScopeId)");
assertIncludes(workbenchSource, "if (selectedSearchIntentScopeId === activeProductScopeId) return;");
assertIncludes(workbenchSource, "<span>经营诊断入口</span>");
assertIncludes(workbenchSource, 'aria-label="经营诊断入口筛选器"');
assertIncludes(workbenchSource, "value={activeProductScopeId}");
assertIncludes(workbenchSource, "onChange={(event) => setSelectedProductScopeId(event.target.value)}");
assertIncludes(workbenchSource, "filterSignalsBySearchIntent(displayProductScopedSignals, activeSearchIntentLabel)");
assertIncludes(workbenchSource, "selectSearchIntentSignalId(displayProductScopedSignals, intentLabel, preferredSearchTerm)");
assertIncludes(workbenchSource, "绑定诊断入口：{selectedProductScopeOption?.label ?? activeProductScopeId}");
assertNotIncludes(workbenchSource, "filterSignalsBySearchIntent(normalizedSignals, intentLabel)");
assertNotIncludes(workbenchSource, 'setFilter("opportunity_expansion");');
assertNotIncludes(workbenchSource, "setSelectedProductScopeId(intentLabel)");
assertNotIncludes(workbenchSource, "setSelectedProductScopeId(card.intentLabel)");
assertNotIncludes(workbenchSource, "value={activeSearchIntentLabel}");
assertNotIncludes(workbenchSource, "value={selectedSearchIntentLabel}");
assertNotIncludes(workbenchSource, "onChange={(event) => setSelectedSearchIntentLabel(event.target.value)}");
assertIncludes(workbenchSource, "fetchSearchIntents(selectedMarketId, nextActiveProductScopeId)");
assertIncludes(workbenchSource, "fetchSearchIntents(selectedMarketId, activeProductScopeId)");
assertNotIncludes(workbenchSource, "fetchSearchIntents()");
assertIncludes(workbenchSource, "Parent ASIN 广告搜索词表现复核");
assertIncludes(workbenchSource, "从当前 Parent ASIN 视角，聚合广告中实际产生表现的用户搜索词");
assertIncludes(workbenchSource, 'aria-label="广告搜索词表现复核数据口径"');
assertIncludes(workbenchSource, "searchIntentPanelContext.purpose");
assertIncludes(workbenchSource, "searchIntentPanelContext.dataGrain");
assertIncludes(workbenchSource, "searchIntentPanelContext.interactionBoundary");
assertIncludes(workbenchSource, "searchIntentPanelContext.proves");
assertIncludes(workbenchSource, "searchIntentPanelContext.doesNotProve");
assertIncludes(workbenchSource, "searchIntentPanelContext.nextManualStep");
assertIncludes(workbenchSource, "searchIntentPanelContext.signalMetricBoundary");
assertIncludes(workbenchSource, "searchIntentPanelContext.boundary");
assertIncludes(workbenchSource, "<b>点击后</b>");
assertIncludes(workbenchSource, 'aria-label="广告搜索词表现复核空态"');
assertIncludes(workbenchSource, "暂无搜索词表现聚合");
assertIncludes(workbenchSource, "诊断入口保持不变，仅显示同类 SearchTerm 信号；不做商品归因");
assertIncludes(workbenchSource, "card.purpose");
assertIncludes(workbenchSource, "card.primarySearchTerm");
assertIncludes(workbenchSource, "card.primarySearchTermReason");
assertIncludes(workbenchSource, 'aria-label="广告搜索词表现运营判断"');
assertIncludes(workbenchSource, "card.operationDecisionLabel");
assertIncludes(workbenchSource, "card.operationDecisionReason");
assertIncludes(workbenchSource, "card.operationDecisionTone");
assertIncludes(workbenchSource, "业务问题：{card.businessQuestion}");
assertIncludes(workbenchSource, "card.currentJudgement");
assertIncludes(workbenchSource, "card.metricPurpose");
assertIncludes(workbenchSource, 'aria-label="广告搜索词表现指标目的"');
assertIncludes(workbenchSource, "card.metricPurposeItems.map");
assertIncludes(workbenchSource, "card.adContext");
assertIncludes(workbenchSource, "card.evidenceGap");
assertIncludes(workbenchSource, "card.signalMetricBoundary");
assertIncludes(workbenchSource, "与具体信号关系");
assertIncludes(workbenchSource, "优先打开");
assertIncludes(workbenchSource, "card.boundary");
assertIncludes(workbenchSource, "广告搜索词表现复核不切换经营商品或广告组");
assertIncludes(workbenchSource, "当前 Parent ASIN 广告搜索词表现复核暂无对应 AI 信号");
assertIncludes(workbenchSource, 'aria-label="Parent ASIN 广告搜索词表现复核"');
assertNotIncludes(workbenchSource, "语义组复核");
assertNotIncludes(workbenchSource, "searchIntentReviewCards.length > 0 && (");
assertNotIncludes(workbenchSource, 'aria-label="搜索词语义聚焦"');
assertNotIncludes(workbenchSource, "聚焦语义组");
assertNotIncludes(workbenchSource, "搜索词机会二级筛选");
assertIncludes(workbenchSource, 'aria-label="Parent ASIN 广告搜索词表现复核背景核对"');
assertIncludes(workbenchSource, 'aria-label="逐投放上下文复核"');
assertIncludes(workbenchSource, "同一个 SearchTerm 可能跨广告活动、广告组和投放词出现");
assertIncludes(workbenchSource, "实际写入以后端 preflight evidence_snapshot_preview 为准");
assertIncludes(workbenchSource, "搜索意图分组不是人工动作对象");
assertNotIncludes(workbenchSource, "当前语义组留痕");
const searchIntentReviewPanelIndex = workbenchSource.indexOf('aria-label="Parent ASIN 广告搜索词表现复核"');
const queueTabsIndex = workbenchSource.indexOf('aria-label="队列筛选"');
const signalRowsIndex = workbenchSource.indexOf('className="signalRows"');
assert(searchIntentReviewPanelIndex > queueTabsIndex, "搜索词表现复核必须跟在队列筛选之后");
assert(searchIntentReviewPanelIndex < signalRowsIndex, "搜索词表现复核必须贴近信号队列，而不是作为独立主入口");
assertNotIncludes(workbenchSource, "setSelectedProductScopeId(allScope.scope_id)");
assertIncludes(workbenchSource, "function handleLocateSignalInCurrentScope");
assertIncludes(workbenchSource, "当前诊断入口下没有命中这条复盘待办对应信号");
assertIncludes(workbenchSource, "当前诊断入口下没有命中推荐候选信号");
assertIncludes(workbenchSource, "当前诊断入口下没有命中下一个候选信号");
assertNotIncludes(workbenchSource, 'setSelectedProductScopeId("all")');
assertIncludes(workbenchSource, "setSelectedProductScopeId(reviewTodoScopeHint.actionScopeId)");
assertIncludes(workbenchSource, "productScopeBusinessPreviewActions");
assertIncludes(workbenchSource, "workbenchGrid focusedFromFirstScreen");
assertIncludes(workbenchSource, 'aria-label="广告证据下钻状态"');
assertIncludes(workbenchSource, "已进入广告诊断工作台");
assertIncludes(workbenchSource, "按广告组、搜索词和广告位证据继续排查");
assertIncludes(workbenchSource, 'aria-label="首屏证据下钻入口"');
assertIncludes(workbenchSource, 'aria-label="广告诊断工作台"');
assertIncludes(workbenchSource, "查看广告组、搜索词和广告位证据");
assertIncludes(workbenchSource, 'aria-label="Parent ASIN 首屏经营摘要"');
assertIncludes(workbenchSource, 'aria-label="首屏广告 ASIN 对比"');
assertIncludes(workbenchSource, 'aria-label="广告 ASIN 覆盖准入判断"');
assertIncludes(workbenchSource, 'aria-label="商品组广告覆盖准入判断"');
assertIncludes(workbenchSource, "adCoverageDecision.statusLabel");
assertIncludes(workbenchSource, "adCoverageDecision.nextManualStep");
assertIncludes(workbenchSource, "下钻判断");
assertIncludes(workbenchSource, "row.decision.statusLabel");
assertIncludes(workbenchSource, "row.decision.reason");
assertIncludes(workbenchSource, "row.decision.nextFocus");
assertIncludes(signalUiSource, "ProductGroupAdAsinDecision");
assertIncludes(signalUiSource, "SearchIntentMetricPurposeItem");
assertIncludes(signalUiSource, "扩量机会指标");
assertIncludes(signalUiSource, "浪费风险指标");
assertIncludes(signalUiSource, "证据缺口提示");
assertIncludes(signalUiSource, "ProductScopeAdCoverageDecision");
assertIncludes(signalUiSource, "buildProductScopeAdCoverageDecision");
assertIncludes(signalUiSource, "未投放子 ASIN 只作为经营背景或覆盖缺口");
assertIncludes(signalUiSource, "不能把搜索词、广告位或 ABA 自动归因到该 ASIN");
assertIncludes(workbenchSource, 'aria-label="首屏诊断路径"');
assertIncludes(workbenchSource, 'aria-label="MVP 落地门禁"');
assertIncludes(workbenchSource, 'aria-label="诊断 MVP 状态判定"');
assertIncludes(workbenchSource, "productScopeFirstScreenSummary.mvpStatus");
assertIncludes(workbenchSource, 'aria-label="广告 ASIN 范围同步提示"');
assertIncludes(workbenchSource, "productScopeSelectionSummary.scopeSyncNotice");
assertIncludes(workbenchSource, 'aria-label="广告 ASIN 候选缺口解释"');
assertIncludes(workbenchSource, "productScopeCandidateGapExplanation");
assertIncludes(workbenchSource, "productScopeBusinessPreviewPath");
assertIncludes(workbenchSource, "productScopeBusinessPreviewPathSummary");
assertIncludes(workbenchSource, "productScopeFirstScreenSummary.pathSummary");
assertIncludes(workbenchSource, "productScopeFirstScreenSummary.pathSteps");
assertIncludes(workbenchSource, "productScopeFirstScreenSummary.landingGates");
assertIncludes(signalUiSource, "Parent ASIN 销售入口 -> 广告 ASIN -> 广告组");
assertIncludes(signalUiSource, "AI 信号诊断 -> 人工确认 -> 7/14 天复盘");
assertIncludes(signalUiSource, "广告组是投放容器，不是产品");
assertIncludes(signalUiSource, "只允许记录观察、标记已处理、加入复盘、忽略本次");
assertIncludes(workbenchSource, 'scope_id: "loading_product_scope"');
assertIncludes(workbenchSource, "正在读取诊断入口");
assertIncludes(workbenchSource, "disabled={productScope === null || loading}");
assertIncludes(workbenchSource, 'aria-label="广告组问题定位"');
assertIncludes(workbenchSource, 'aria-label="广告组问题归属判定"');
assertIncludes(workbenchSource, "row.ownershipDecision.statusLabel");
assertIncludes(workbenchSource, "row.ownershipDecision.issueOwner");
assertIncludes(workbenchSource, "row.ownershipDecision.evidencePath");
assertIncludes(workbenchSource, "row.ownershipDecision.nextManualStep");
assertIncludes(signalUiSource, "ProductScopeAdGroupOwnershipDecision");
assertIncludes(signalUiSource, "productScopeAdGroupOwnershipDecision");
assertIncludes(signalUiSource, "问题先归属到广告组容器和搜索词上下文");
assertIncludes(workbenchSource, 'aria-label="广告组问题落点"');
assertIncludes(workbenchSource, "row.problemLocator.problemLocation");
assertIncludes(workbenchSource, "row.problemLocator.splitReason");
assertIncludes(workbenchSource, "row.problemLocator.doesNotProve");
assertIncludes(workbenchSource, "row.problemLocator.nextManualStep");
assertIncludes(signalUiSource, "ProductScopeAdGroupProblemLocator");
assertIncludes(signalUiSource, "不能证明应自动拆广告组");
assertIncludes(workbenchSource, 'aria-label="广告组证据合流判断"');
assertIncludes(workbenchSource, "row.evidenceSynthesis.statusLabel");
assertIncludes(workbenchSource, "row.evidenceSynthesis.evidenceChain");
assertIncludes(workbenchSource, "row.evidenceSynthesis.evidenceGap");
assertIncludes(signalUiSource, "ProductScopeAdGroupEvidenceSynthesis");
assertIncludes(signalUiSource, "广告商品、投放词、搜索词和广告位证据是否指向同一个可人工复核的问题");
assertIncludes(signalUiSource, "证据合流：搜索词分化优先");
assertIncludes(workbenchSource, 'aria-label="广告组人工复核判断"');
assertIncludes(workbenchSource, 'aria-label="搜索词问题定位"');
assertIncludes(workbenchSource, 'aria-label="搜索词业务判断"');
assertIncludes(workbenchSource, 'aria-label="广告搜索词表现复核链"');
assertIncludes(workbenchSource, "buildSearchTermOpportunityReviewChain");
assertIncludes(workbenchSource, "SearchTermOpportunityReviewChainPanel");
assertIncludes(workbenchSource, "<b>复核路径</b>");
assertIncludes(workbenchSource, "<b>Parent ASIN 入口</b>");
assertIncludes(workbenchSource, "<b>广告 ASIN 承接</b>");
assertIncludes(workbenchSource, "<b>广告组合流判断</b>");
assertIncludes(workbenchSource, "<b>同组投放商品表现</b>");
assertIncludes(workbenchSource, "<b>广告位边界</b>");
assertIncludes(workbenchSource, "chain.reviewPath");
assertIncludes(workbenchSource, "chain.parentScopeContext");
assertIncludes(workbenchSource, "chain.adAsinCoverage");
assertIncludes(workbenchSource, "chain.adGroupSynthesis");
assertIncludes(workbenchSource, "chain.adGroupProductPerformance");
assertIncludes(workbenchSource, "chain.placementBoundary");
assertIncludes(workbenchSource, "chain.marketContext");
assertIncludes(workbenchSource, "chain.actionBoundary");
assert(
  workbenchSource.indexOf("chain.reviewPath") < workbenchSource.indexOf("chain.parentScopeContext") &&
    workbenchSource.indexOf("chain.parentScopeContext") < workbenchSource.indexOf("chain.adAsinCoverage") &&
    workbenchSource.indexOf("chain.adAsinCoverage") < workbenchSource.indexOf("chain.adGroupSynthesis") &&
    workbenchSource.indexOf("chain.adGroupSynthesis") < workbenchSource.indexOf("chain.adGroupProductPerformance") &&
    workbenchSource.indexOf("chain.adGroupProductPerformance") < workbenchSource.indexOf("chain.targetingEvidence") &&
    workbenchSource.indexOf("chain.targetingEvidence") < workbenchSource.indexOf("chain.placementBoundary") &&
    workbenchSource.indexOf("chain.placementBoundary") < workbenchSource.indexOf("chain.marketContext"),
  "广告搜索词表现复核链必须先展示复核路径，再按 Parent ASIN -> 广告 ASIN -> 广告组合流判断 -> 同组投放商品表现 -> 投放词证据 -> 广告位边界 -> ABA 背景 的顺序展示。",
);
assertIncludes(workbenchSource, "diagnosis.decision.businessQuestion");
assertIncludes(workbenchSource, "diagnosis.decision.targetingEvidence");
assertIncludes(workbenchSource, "diagnosis.decision.proves");
assertIncludes(workbenchSource, "diagnosis.decision.doesNotProve");
assertIncludes(workbenchSource, "diagnosis.decision.nextManualStep");
assertIncludes(signalUiSource, "ProductScopeSearchTermDecision");
assertIncludes(signalUiSource, "SearchTermOpportunityReviewChain");
assertIncludes(signalUiSource, "不能把 ABA 当作店铺数据");
assertIncludes(signalUiSource, "站点 + 周期 + 标准化搜索词");
assertIncludes(signalUiSource, "不能证明应自动加词");
assertIncludes(workbenchSource, 'aria-label="广告位证据判断"');
assertIncludes(workbenchSource, "row.placementDecision.evidenceLevel");
assertIncludes(workbenchSource, "row.placementDecision.doesNotProve");
assertIncludes(workbenchSource, "row.placementDecision.evidenceGap");
assertIncludes(workbenchSource, "row.placementDecision.nextManualStep");
assertIncludes(signalUiSource, "ProductScopePlacementEvidenceDecision");
assertIncludes(signalUiSource, "只有广告活动级广告位背景");
assertIncludes(signalUiSource, "不能把广告位影响自动归因到单个搜索词或广告 ASIN");
assertIncludes(workbenchSource, 'aria-label="人工候选与广告组关系"');
assertIncludes(workbenchSource, 'aria-label="人工动作目标切换提示"');
assertIncludes(workbenchSource, "manualActionQueueTargetSwitchSummary");
assertIncludes(workbenchSource, "manualActionTargetSwitch");
assertIncludes(workbenchSource, 'aria-label="人工确认双轨分流"');
assertIncludes(workbenchSource, "manualActionReviewRouteSplitSummary");
assertIncludes(workbenchSource, "manualActionRouteSplit");
assertIncludes(workbenchSource, 'aria-label="人工动作待授权写入状态"');
assertIncludes(workbenchSource, "manualActionAuthorizationReadinessSummary");
assertIncludes(workbenchSource, "manualActionAuthorizationReadiness");
assertIncludes(workbenchSource, 'aria-label="人工点击前广告组合流复核"');
assertIncludes(workbenchSource, "selectedManualActionAdGroupBridge.synthesisStatus");
assertIncludes(workbenchSource, "selectedManualActionAdGroupBridge.synthesisEvidenceChain");
assertIncludes(workbenchSource, "selectedManualActionAdGroupBridge.synthesisBoundary");
assertIncludes(workbenchSource, "selectedManualActionAdGroupBridge.synthesisGap");
assertIncludes(workbenchSource, "selectedManualActionAdGroupBridge.searchTermBoundary");
assertIncludes(workbenchSource, "selectedManualActionAdGroupBridge.placementBoundary");
assertIncludes(workbenchSource, "selectedManualActionAdGroupBridge.manualNextStep");
assertIncludes(signalUiSource, "沿用中间广告组合流判断");
assertIncludes(signalUiSource, "synthesis.statusLabel");
assertIncludes(signalUiSource, "synthesis.evidenceChain");
assertIncludes(signalUiSource, "searchTermDecision?.nextManualStep");
assertIncludes(signalUiSource, "topGroup.placementDecision.nextManualStep");
assertIncludes(signalUiSource, "右侧按钮只保存人工留痕或复盘待办");
assertIncludes(workbenchSource, "buildManualReviewClosureLedger");
assertIncludes(workbenchSource, "buildReviewReadinessGateSummary");
assertIncludes(workbenchSource, "buildReviewEvidenceRepairSummary");
assertIncludes(workbenchSource, "selectedManualReviewClosureLedger");
assertIncludes(workbenchSource, "reviewReadinessGateSummary");
assertIncludes(workbenchSource, "reviewEvidenceRepairSummary");
assertIncludes(workbenchSource, "queueBusinessFilters");
assertIncludes(workbenchSource, "机会扩量");
assertIncludes(workbenchSource, "花费浪费");
assertIncludes(workbenchSource, "投放结构");
assertIncludes(workbenchSource, "数据质量");
assertIncludes(workbenchSource, "复盘");
assertIncludes(workbenchSource, 'aria-label="全局复盘可验证性"');
assertIncludes(workbenchSource, "reviewReadinessGateSummary");
assertIncludes(workbenchSource, "reviewEvidenceRepairAriaLabel");
assertIncludes(workbenchSource, "历史待办治理：仍被复盘证据门禁阻断");
assertIncludes(workbenchSource, "reviewReadinessGateSummary reviewEvidenceRepairSummary");
assertIncludes(workbenchSource, "aria-label={reviewEvidenceRepairAriaLabel}");
assertIncludes(workbenchSource, 'aria-label="历史待办 dry-run 核对清单"');
assertIncludes(workbenchSource, "reviewEvidenceRepairSummary.voidPlanItems");
assertIncludes(workbenchSource, "reviewRepairDryRunChecklist");
assertIncludes(workbenchSource, "<dt>计划状态</dt>");
assertIncludes(workbenchSource, "item.statusText");
assertIncludes(workbenchSource, "<dt>作废后</dt>");
assertIncludes(workbenchSource, "item.afterVoidText");
assertIncludes(workbenchSource, "<dt>重新留痕</dt>");
assertIncludes(workbenchSource, "item.recreateText");
assertIncludes(workbenchSource, "item.dryRunCommand");
assertIncludes(workbenchSource, "ReviewRepairSampleItem");
assertIncludes(workbenchSource, "buildReviewRepairSampleSections");
assertIncludes(workbenchSource, 'aria-label="历史待办治理样本"');
assertIncludes(workbenchSource, "reviewRepairSampleList");
assertIncludes(workbenchSource, "reviewRepairSampleSection");
assertIncludes(workbenchSource, "<ReviewRepairSampleItem item={item} />");
assertIncludes(workbenchSource, 'aria-label="历史待办治理下一步"');
const reviewGateRenderIndex = workbenchSource.indexOf('aria-label="全局复盘可验证性"');
const reviewEvidenceRepairRenderIndex = workbenchSource.indexOf("aria-label={reviewEvidenceRepairAriaLabel}");
assert(
  reviewGateRenderIndex >= 0 &&
    reviewEvidenceRepairRenderIndex >= 0 &&
    reviewGateRenderIndex < reviewEvidenceRepairRenderIndex,
  "右侧复盘状态必须先展示复盘证据门禁，再展示历史待办治理，避免把 ready_no_legacy_gap 误读成可保存 ReviewRecord。",
);
assertIncludes(workbenchSource, "fetchReviewEvidenceRepair");
assertNotIncludes(workbenchSource, "/review-todos/void");
assertIncludes(workbenchSource, 'aria-label="复盘读回身份门禁"');
assertIncludes(workbenchSource, "reviewReadinessGateSummary.identityAudit");
assertIncludes(workbenchSource, 'aria-label="复盘下一步路径"');
assertIncludes(workbenchSource, "reviewReadinessNextSteps");
assertIncludes(workbenchSource, "snapshotActionBoundaryText");
assertIncludes(workbenchSource, "shouldPauseSnapshotPullForReview");
assertIncludes(workbenchSource, "snapshotActionBoundary");
assertIncludes(workbenchSource, 'aria-label="快照复盘门禁"');
assertIncludes(workbenchSource, 'aria-label="人工确认复盘闭环三层"');
assertIncludes(workbenchSource, "manualReviewClosureLedger");
assertIncludes(workbenchSource, '有效搜索词');
assertIncludes(workbenchSource, '无订单花费词');
assertIncludes(workbenchSource, 'aria-label="无候选人工动作门禁"');
assertIncludes(workbenchSource, 'aria-label="人工确认证据依据"');
assertIncludes(workbenchSource, "buildManualConfirmationEvidenceItems");
assertIncludes(workbenchSource, "selectedSearchTermOpportunityReviewChain");
assertIncludes(workbenchSource, "buildManualConfirmationEvidenceItems(selectedDiagnosisContractItems, selectedSearchTermOpportunityReviewChain, selectedSignal)");
assertIncludes(workbenchSource, 'aria-label="对象复核路径"');
assertIncludes(signalUiSource, "buildSignalObjectReviewPath");
assertIncludes(signalUiSource, "Parent ASIN 销售盘 -> 当前广告 ASIN");
assertIncludes(signalUiSource, "Parent ASIN 销售盘 -> 广告 ASIN 覆盖 -> 当前广告组容器");
assertIncludes(signalUiSource, "不能自动拆广告组");
assertIncludes(signalUiSource, "当前经营入口 -> 广告活动 / 广告组 -> 广告位表现");
assertIncludes(workbenchSource, 'aria-label="人工确认证据写入核对"');
assertIncludes(workbenchSource, "manualConfirmationEvidenceReadinessSummary");
assertIncludes(workbenchSource, "selectedManualActionFullPreflightEvidenceRows");
assertIncludes(workbenchSource, "manualConfirmationEvidenceReadiness");
assertIncludes(workbenchSource, 'aria-label="诊断到人工留痕证据同步"');
assertIncludes(workbenchSource, "manualConfirmationDiagnosisBridgeSummary");
assertIncludes(workbenchSource, "selectedDiagnosisEvidenceSummary");
assertIncludes(workbenchSource, "selectedManualConfirmationDiagnosisBridge");
assertIncludes(workbenchSource, "manualConfirmationDiagnosisBridge");
assertIncludes(workbenchSource, "buildManualActionDecisionFactItems");
assertIncludes(workbenchSource, "selectedManualActionDecisionFactItems");
assertIncludes(workbenchSource, "selectedManualActionDecisionFactItems.map");
assertIncludes(signalUiSource, "ManualActionDecisionFactItem");
assertIncludes(signalUiSource, "业务问题：");
assertIncludes(signalUiSource, "当前判断：");
assertIncludes(signalUiSource, "证据摘要：");
assertIncludes(signalUiSource, "不能证明：");
assertIncludes(signalUiSource, "证据缺口：");
assertNotIncludes(workbenchSource, "{selectedSignal.risk}");
assertNotIncludes(workbenchSource, "{selectedSignal.uncertainty}");
assertIncludes(workbenchSource, "nextUnhandledDiagnosisContractItems");
assertIncludes(workbenchSource, "selectedSignal.id === signalTriageSummary?.next_unhandled_candidate?.signal_id");
assertNotIncludes(workbenchSource, "selectedSignal.id === signalTriageSummary?.recommended_candidate?.signal_id ? recommendedDiagnosisContractItems : []");
assertIncludes(workbenchSource, "buildSignalDiagnosisEvidenceSummary");
assertIncludes(workbenchSource, "diagnosisEvidenceSummary");
assertIncludes(workbenchSource, 'aria-label="业务判断与指标目的"');
assertIncludes(workbenchSource, "业务判断与指标目的");
assertIncludes(workbenchSource, "先回答这条信号要判断什么");
assertIncludes(workbenchSource, 'aria-label="证据强度和判断边界摘要"');
assertIncludes(workbenchSource, "诊断对象");
assertIncludes(workbenchSource, "objectReadback");
assertIncludes(workbenchSource, "强度依据");
assertIncludes(workbenchSource, "能证明");
assertIncludes(workbenchSource, "不能证明");
assertIncludes(workbenchSource, "人工下一步");
assertIncludes(workbenchSource, "指标目的：");
assertIncludes(workbenchSource, "当前判断：");
assertIncludes(workbenchSource, 'aria-label="人工留痕动作"');
assertIncludes(workbenchSource, "只保存人工留痕和复盘待办，不执行广告动作");
assertIncludes(workbenchSource, "manualActionEmptyStateText(manualActionPreflight)");
assertIncludes(workbenchSource, "reviewTodoEmptyStateText(latestManualAction)");
assertIncludes(workbenchSource, "buildManualActionPathSteps");
assertIncludes(workbenchSource, "buildManualActionReadbackPathItems");
assertIncludes(workbenchSource, "buildManualActionIdentityGateItems");
assertIncludes(workbenchSource, "manualActionPreflightsByAction");
assertIncludes(workbenchSource, "manualActionPreflightErrorsByAction");
assertIncludes(workbenchSource, "manualActionPreviewActionType");
assertIncludes(workbenchSource, "selectedManualActionPreviewActionType");
assertIncludes(workbenchSource, "selectedManualActionPreviewPreflight");
assertIncludes(workbenchSource, "function handleLocateReviewSignal");
assertIncludes(workbenchSource, 'aria-label={`定位复盘待办 ${reviewTodoQueueSummary.nextLabel}`}');
assertIncludes(workbenchSource, "handleLocateReviewSignal(reviewTodoQueueSummary.next?.signal_id)");
assertIncludes(workbenchSource, "handleLocateReviewSignal(row.signalId)");
assertIncludes(workbenchSource, "const selectedReviewEvidenceSnapshot = useMemo");
assertIncludes(workbenchSource, "reviewEvidenceSnapshot={selectedReviewEvidenceSnapshot?.items ?? []}");
assertIncludes(workbenchSource, 'aria-label="复盘点击时证据快照"');
assertIncludes(workbenchSource, 'title: "复盘点击时证据快照"');
assertIncludes(workbenchSource, "不是当前实时广告事实，也不是效果结论");
assertIncludes(workbenchSource, "来自 ReviewTodo 继承的人工点击时证据快照");
assertIncludes(workbenchSource, "buildReviewTodoEvidenceReadbackSummary");
assertIncludes(workbenchSource, "selectedReviewTodoEvidenceReadback");
assertIncludes(workbenchSource, 'aria-label="复盘待办证据回读核对"');
assertIncludes(workbenchSource, "reviewTodoEvidenceReadback");
assertIncludes(workbenchSource, "signalTriageSummary?.recommended_diagnosis_contract");
assertIncludes(workbenchSource, "signalTriageSummary?.next_unhandled_diagnosis_contract");
assertNotIncludes(workbenchSource, "const diagnosisContractSignalId");
assertIncludes(workbenchSource, "const fetchPreflightForAction = async (actionType: ManualActionType)");
assertIncludes(workbenchSource, "const recommendedResult = await fetchPreflightForAction(recommendedActionType)");
assertIncludes(workbenchSource, "setManualActionPreflight(recommendedResult.preflight)");
assertIncludes(workbenchSource, "manualActionOrder.filter((actionType) => actionType !== recommendedActionType)");
assertIncludes(workbenchSource, "manualActionPreflightForAction(actionType");
assertIncludes(workbenchSource, "manualActionPreflightErrorForAction(");
assertIncludes(workbenchSource, "manualActionButtonExpectationText(actionType");
assertIncludes(workbenchSource, "actionGate.compactReason ?? actionExpectationText");
assertIncludes(workbenchSource, "当前预览动作");
assertIncludes(workbenchSource, "当前 SearchTerm 已有人工留痕");
assertIncludes(workbenchSource, "当前信号没有后端可写预检对象");
assertIncludes(workbenchSource, "manualActionDisplayLabel(selectedBackendManualActionPreview.actionType)");
assertIncludes(workbenchSource, "/ 不执行广告动作");
assertIncludes(workbenchSource, "setManualActionPreviewActionType(actionType)");
assertIncludes(workbenchSource, "onFocus={() => setManualActionPreviewActionType(actionType)}");
assertIncludes(workbenchSource, "onMouseEnter={() => setManualActionPreviewActionType(actionType)}");
assertIncludes(workbenchSource, "manualActionPreflightEvidenceRows(selectedManualActionPreviewPreflight)");
assertIncludes(workbenchSource, 'aria-label="优先查看的边界与证据缺口"');
assertIncludes(workbenchSource, "先看边界与缺口");
assertIncludes(reviewUiSource, '"搜索词边界"');
assertIncludes(reviewUiSource, '"广告位边界"');
assertIncludes(reviewUiSource, '"广告位证据缺口"');
assertIncludes(workbenchSource, "manualActionPostWriteContractItems(selectedManualActionPreviewPreflight)");
assertIncludes(workbenchSource, 'aria-label="人工处理路径"');
assertIncludes(workbenchSource, 'aria-label="点击后读回路径"');
assertIncludes(workbenchSource, 'aria-label="人工动作对象身份门禁"');
assertIncludes(workbenchSource, "buildReviewRecordSaveGateSummary");
assertIncludes(workbenchSource, "buildReviewEffectWindowLedger");
assertIncludes(workbenchSource, "selectedReviewEffectWindowLedger");
assertIncludes(workbenchSource, "hasReviewRecordReadbackMatch");
assertIncludes(workbenchSource, "selectedReviewRecordSaveGate.canSave");
assertIncludes(workbenchSource, 'aria-label="复盘效果窗口口径"');
assertIncludes(workbenchSource, "reviewEffectWindowLedger");
assertIncludes(workbenchSource, 'aria-label="复盘保存门槛"');
assertNotIncludes(workbenchSource, "<p>暂无人工处理记录</p>");
